# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Anil Kunchala
description:      'a <i> Tinkerers </i> log about his experiments with few things he came across'
url:              https://anilkunchalaece.github.io

author:
  name:           'Anil Kunchala'
  url:            https://twitter.com/anilkunchalaece

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

disqus.shortname: 'anil'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
